#!/usr/bin/env python3
"""Generate src/rtl/EMU/sine_key_synth.v (256-point sine DDS + key map)."""

from __future__ import annotations

import math
from pathlib import Path

LUT_SIZE = 256
AMPLITUDE = 16384
HCLK_HZ = 16_777_216  # Gowin PLL clkout2 from 33.554432 MHz / 2

# Equal temperament, A4 = 440 Hz. Phase step = round(f * 2^32 / hclk).
NOTES = [
    ("C4", 60),
    ("D4", 62),
    ("E4", 64),
    ("F4", 65),
    ("G4", 67),
    ("A4", 69),
    ("B4", 71),
    ("C5", 72),
]


def midi_hz(midi: int) -> float:
    return 440.0 * (2.0 ** ((midi - 69) / 12.0))


def phase_step(hz: float) -> int:
    return round(hz * (1 << 32) / HCLK_HZ)


def sd16(value: int) -> str:
    if value < 0:
        return f"-16'sd{-value}"
    return f"16'sd{value}"


def sine_lut() -> list[int]:
    scale = AMPLITUDE
    return [
        int(round(scale * math.sin(2.0 * math.pi * i / LUT_SIZE)))
        for i in range(LUT_SIZE)
    ]


def render() -> str:
    steps = [(name, phase_step(midi_hz(midi))) for name, midi in NOTES]
    lut = sine_lut()

    step_params = "\n".join(
        f"    localparam [31:0] STEP_{name} = 32'd{step};" for name, step in steps
    )
    lut_assigns = "\n".join(
        f"        sine_lut[8'd{i}] = {sd16(v)};" for i, v in enumerate(lut)
    )
    vis_assigns = "\n".join(
        f"        vis_lut[8'd{i}] = {sd16(v)};" for i, v in enumerate(lut)
    )

    return f"""// Generated by scripts/gen_sine_key_synth.py. Do not edit by hand.
// One-channel key synth: held buttons play C4-C5 as a sine DDS.
// hclk is {HCLK_HZ / 1e6:.6f} MHz; phase step is round(f * 2^32 / hclk) = round(f * 256).
// Mapping: Left C4, Down D4, Up E4, Right F4, Select G4, Start A4, B B4, A C5.
// Simultaneous keys: the higher note wins.
// lut_q is a 1-cycle read of the same table, for the oscilloscope.
// Audio is shifted down so a sustained tone does not sag the supply.

module sine_key_synth
(
    input               clk,
    input               reset_n,
    input               enable,
    input               btn_left,
    input               btn_down,
    input               btn_up,
    input               btn_right,
    input               btn_sel,
    input               btn_start,
    input               btn_b,
    input               btn_a,
    output reg signed [15:0] sample,
    output     [31:0]   dds_phase,
    output     [31:0]   dds_step,
    input      [7:0]    lut_index,
    output reg signed [15:0] lut_q
);

{step_params}

    reg signed [15:0] sine_lut [0:255];
    reg signed [15:0] vis_lut [0:255];
    initial begin
{lut_assigns}
{vis_assigns}
    end

    wire [31:0] step =
        btn_a     ? STEP_C5 :
        btn_b     ? STEP_B4 :
        btn_start ? STEP_A4 :
        btn_sel   ? STEP_G4 :
        btn_right ? STEP_F4 :
        btn_up    ? STEP_E4 :
        btn_down  ? STEP_D4 :
        btn_left  ? STEP_C4 :
                    32'd0;

    wire key_held = |{{btn_a, btn_b, btn_start, btn_sel, btn_right, btn_up, btn_down, btn_left}};

    reg [31:0] phase;
    assign dds_phase = phase;
    assign dds_step  = step;

    // Full-scale LUT is ±16384. >> 3 keeps the speaker near ±2048.
    localparam integer AUDIO_SHIFT = 3;

    always @(posedge clk or negedge reset_n) begin
        if (!reset_n) begin
            phase  <= 32'd0;
            sample <= 16'sd0;
            lut_q  <= 16'sd0;
        end else begin
            lut_q <= vis_lut[lut_index];
            if (!enable || !key_held) begin
                phase  <= 32'd0;
                sample <= 16'sd0;
            end else begin
                phase  <= phase + step;
                sample <= sine_lut[phase[31:24]] >>> AUDIO_SHIFT;
            end
        end
    end

endmodule
"""


def main() -> None:
    root = Path(__file__).resolve().parents[1]
    out = root / "src" / "rtl" / "EMU" / "sine_key_synth.v"
    text = render()
    out.write_text(text)
    print(f"wrote {out.relative_to(root)} ({len(text.splitlines())} lines)")


if __name__ == "__main__":
    main()
